language:
- cpp
dist:
- trusty
compiler:
- gcc
before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get -qq update
install:
- sudo apt-get install -y autoconf-archive
- sudo apt-get install -y libboost-all-dev
- sudo apt-get install -y libsndfile1-dev
- sudo apt-get install -qq g++-6
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
script:
- make -C KissFFT/examples clean all V=1 CC=${CC} CXX=${CXX}
- make -C src clean all V=1 CC=${CC} CXX=${CXX}
after_success:
- bin/upsampling_algorithm_short_sequence octave/sine_48000_pcm32_short.wav
